str_set1: ext
str_set0: ext
str_play: ext
str_rules: ext
str_pause: ext
str_inv: ext
str_step: ext
str_su: ext
str_sd: ext
str_ss: ext
str_clr: ext
str_srect1: ext
str_srect0: ext
str_help: ext
str_savex: ext
str_loadx: ext
str_input: ext
str_help_txt: ext
str_succ: ext
str_hello: ext
error_large_coord: ext
error_inc_inp: ext
error_few_args: ext
error_no_args: ext
error_inc_com: ext
error_no_com: ext
error_many_args: ext
error_large_num: ext
error_x_higher: ext
error_y_higher: ext
error_many_chars: ext
error_slot_is_empty: ext
error_template_too_big_x: ext
error_template_too_big_y: ext
